train_dataloader: 
  dataset: 
    return_masks: False
    transforms:
      ops:
        - {type: RandomPhotometricDistort, p: 0.5}
        - {type: RandomZoomOut, fill: 0}
        - {type: RandomIoUCrop, p: 0.8}
        - {type: SanitizeBoundingBox, min_size: 1}
        - {type: RandomHorizontalFlip}
        - {type: Resize, size: [640, 640], }
        # - {type: Resize, size: 639, max_size: 640}
        # - {type: PadToSize, spatial_size: 640}
        - {type: ToImageTensor}
        - {type: ConvertDtype}
        - {type: SanitizeBoundingBox, min_size: 1}
        - {type: ConvertBox, out_fmt: 'cxcywh', normalize: True}

    # CL change here
    data_ratio: "15071"
    task_idx: 1
    buffer_mode: True
    buffer_rate: 0.1
    buffer_img_path: "./buffer"
    buffer_ann_file: "./buffer.json"
        
  shuffle: True
  batch_size: 8
  num_workers: 12
  collate_fn: default_collate_fn
  drop_last: True

val_dataloader:
  dataset:
    transforms:
      ops:
        - { type: Resize, size: [640, 640] }
        - { type: ToImageTensor }
        - { type: ConvertDtype }

    # CL change here
    data_ratio: "15071"
    task_idx: 1
    buffer_mode: False

  shuffle: False
  batch_size: 48
  num_workers: 12
  collate_fn: default_collate_fn
  drop_last: False