task: detection

num_classes: 221
    
remap_mscoco_category: True

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetectionCL

    img_folder: ./mapillary-traffic-sign-dataset/mtsd_fully_annotated_train_images/images
    ann_file: ./mtsd-preprocessing/train_output_file_coco.json
    transforms:
      type: Compose
      ops: ~

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetectionCL

    img_folder: ./mapillary-traffic-sign-dataset/mtsd_v2_fully_annotated_images.val.zip/images
    ann_file: ./mtsd-preprocessing/val_output_file_coco.json
    transforms:
      type: Compose
      ops: ~