# CL General
start_task: 0
total_tasks: 2

# CL Strategy
pseudo_label: True
distill_attn: True
teacher_path: "./checkpoint-for-mtsd-model/scheme2_221_classes_15071_t0_3e_ap15.33.pth"

# CL Rehearsal 
rehearsal: False

# CL Eval
fpp: False

# WandB
wandb_name: "7010_t1_10e"